# FOS User Configuration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: JZK\Bundle\Core\UserBundle\Entity\User
    group:
        group_class: JZK\Bundle\Core\UserBundle\Entity\Group