parameters:
#    three_dots_demo.example.class: ThreeDots\DemoBundle\Example

services:
#    three_dots_demo.example:
#        class: %three_dots_demo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
